vars:
  BUNDLE_ID:
    default: com.mnazbro.film.friend
  PACKAGE_NAME:
    default: com.mnazbro.film.friend

platforms:
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
        incrementBuild: true
        version: "1.0"
        displayName: Film Friend

  android:
    appName: Film Friend
    packageName: $PACKAGE_NAME
    versionName: "1.0"
    incrementVersionCode: true
