/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FlashRouteImport } from './routes/flash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CameraIndexRouteImport } from './routes/camera/index'
import { Route as CameraSelectRouteImport } from './routes/camera/select'
import { Route as CameraNewRouteImport } from './routes/camera/new'
import { Route as CameraCameraIdIndexRouteImport } from './routes/camera/$cameraId/index'
import { Route as CameraCameraIdRollNewRouteImport } from './routes/camera/$cameraId/roll/new'
import { Route as CameraCameraIdRollRollIdRouteImport } from './routes/camera/$cameraId/roll/$rollId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashRoute = FlashRouteImport.update({
  id: '/flash',
  path: '/flash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraIndexRoute = CameraIndexRouteImport.update({
  id: '/camera/',
  path: '/camera/',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraSelectRoute = CameraSelectRouteImport.update({
  id: '/camera/select',
  path: '/camera/select',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraNewRoute = CameraNewRouteImport.update({
  id: '/camera/new',
  path: '/camera/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraCameraIdIndexRoute = CameraCameraIdIndexRouteImport.update({
  id: '/camera/$cameraId/',
  path: '/camera/$cameraId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraCameraIdRollNewRoute = CameraCameraIdRollNewRouteImport.update({
  id: '/camera/$cameraId/roll/new',
  path: '/camera/$cameraId/roll/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraCameraIdRollRollIdRoute =
  CameraCameraIdRollRollIdRouteImport.update({
    id: '/camera/$cameraId/roll/$rollId',
    path: '/camera/$cameraId/roll/$rollId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flash': typeof FlashRoute
  '/settings': typeof SettingsRoute
  '/camera/new': typeof CameraNewRoute
  '/camera/select': typeof CameraSelectRoute
  '/camera': typeof CameraIndexRoute
  '/camera/$cameraId': typeof CameraCameraIdIndexRoute
  '/camera/$cameraId/roll/$rollId': typeof CameraCameraIdRollRollIdRoute
  '/camera/$cameraId/roll/new': typeof CameraCameraIdRollNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flash': typeof FlashRoute
  '/settings': typeof SettingsRoute
  '/camera/new': typeof CameraNewRoute
  '/camera/select': typeof CameraSelectRoute
  '/camera': typeof CameraIndexRoute
  '/camera/$cameraId': typeof CameraCameraIdIndexRoute
  '/camera/$cameraId/roll/$rollId': typeof CameraCameraIdRollRollIdRoute
  '/camera/$cameraId/roll/new': typeof CameraCameraIdRollNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flash': typeof FlashRoute
  '/settings': typeof SettingsRoute
  '/camera/new': typeof CameraNewRoute
  '/camera/select': typeof CameraSelectRoute
  '/camera/': typeof CameraIndexRoute
  '/camera/$cameraId/': typeof CameraCameraIdIndexRoute
  '/camera/$cameraId/roll/$rollId': typeof CameraCameraIdRollRollIdRoute
  '/camera/$cameraId/roll/new': typeof CameraCameraIdRollNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flash'
    | '/settings'
    | '/camera/new'
    | '/camera/select'
    | '/camera'
    | '/camera/$cameraId'
    | '/camera/$cameraId/roll/$rollId'
    | '/camera/$cameraId/roll/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flash'
    | '/settings'
    | '/camera/new'
    | '/camera/select'
    | '/camera'
    | '/camera/$cameraId'
    | '/camera/$cameraId/roll/$rollId'
    | '/camera/$cameraId/roll/new'
  id:
    | '__root__'
    | '/'
    | '/flash'
    | '/settings'
    | '/camera/new'
    | '/camera/select'
    | '/camera/'
    | '/camera/$cameraId/'
    | '/camera/$cameraId/roll/$rollId'
    | '/camera/$cameraId/roll/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlashRoute: typeof FlashRoute
  SettingsRoute: typeof SettingsRoute
  CameraNewRoute: typeof CameraNewRoute
  CameraSelectRoute: typeof CameraSelectRoute
  CameraIndexRoute: typeof CameraIndexRoute
  CameraCameraIdIndexRoute: typeof CameraCameraIdIndexRoute
  CameraCameraIdRollRollIdRoute: typeof CameraCameraIdRollRollIdRoute
  CameraCameraIdRollNewRoute: typeof CameraCameraIdRollNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash': {
      id: '/flash'
      path: '/flash'
      fullPath: '/flash'
      preLoaderRoute: typeof FlashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera/': {
      id: '/camera/'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera/select': {
      id: '/camera/select'
      path: '/camera/select'
      fullPath: '/camera/select'
      preLoaderRoute: typeof CameraSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera/new': {
      id: '/camera/new'
      path: '/camera/new'
      fullPath: '/camera/new'
      preLoaderRoute: typeof CameraNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera/$cameraId/': {
      id: '/camera/$cameraId/'
      path: '/camera/$cameraId'
      fullPath: '/camera/$cameraId'
      preLoaderRoute: typeof CameraCameraIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera/$cameraId/roll/new': {
      id: '/camera/$cameraId/roll/new'
      path: '/camera/$cameraId/roll/new'
      fullPath: '/camera/$cameraId/roll/new'
      preLoaderRoute: typeof CameraCameraIdRollNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera/$cameraId/roll/$rollId': {
      id: '/camera/$cameraId/roll/$rollId'
      path: '/camera/$cameraId/roll/$rollId'
      fullPath: '/camera/$cameraId/roll/$rollId'
      preLoaderRoute: typeof CameraCameraIdRollRollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashRoute: FlashRoute,
  SettingsRoute: SettingsRoute,
  CameraNewRoute: CameraNewRoute,
  CameraSelectRoute: CameraSelectRoute,
  CameraIndexRoute: CameraIndexRoute,
  CameraCameraIdIndexRoute: CameraCameraIdIndexRoute,
  CameraCameraIdRollRollIdRoute: CameraCameraIdRollRollIdRoute,
  CameraCameraIdRollNewRoute: CameraCameraIdRollNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
